Fix creditLineCount undefined in delete invoice
Whilst regression testing v0.18.0 we came across this error

```
TypeError: Cannot read properties of undefined (reading 'creditLineCount')
at Function._billRunPatch (/home/node/app/app/services/invoices/delete_invoice.service.js:82:61)
at Function._deleteInvoice (/home/node/app/app/services/invoices/delete_invoice.service.js:46:31)
at /home/node/app/app/services/invoices/delete_invoice.service.js:36:22
at /home/node/node_modules/knex/lib/transaction.js:183:22
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'id')
at Function.go (/home/node/app/app/services/invoices/delete_invoice.service.js:41:61)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

This change fixes the issue.