Fix creditLineCount undefined in delete invoice (#708)
Whilst regression testing v0.18.0 we came across this error

```
TypeError: Cannot read properties of undefined (reading 'creditLineCount')
at Function._billRunPatch (/home/node/app/app/services/invoices/delete_invoice.service.js:82:61)
at Function._deleteInvoice (/home/node/app/app/services/invoices/delete_invoice.service.js:46:31)
at /home/node/app/app/services/invoices/delete_invoice.service.js:36:22
at /home/node/node_modules/knex/lib/transaction.js:183:22
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'id')
at Function.go (/home/node/app/app/services/invoices/delete_invoice.service.js:41:61)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

We had overlooked updating the code in the controller to _not_ depend on what the validation service returns (because it doesn't return anything) in [Change FetchAndValidateInvoiceService to ValidateInvoiceService](https://github.com/DEFRA/sroc-charging-module-api/pull/699).

This meant we were validating that the invoice could be deleted and returning a `2xx` response but then erroring because we were passing in `undefined` to actually be deleted.