Move nock to be a required dependency
Again, related to a 'production' level endpoint trying to make use of things normally only used in 'test' we get an error if you try and run the app in the docker image. This time the error is

```
uncaught exception Error: Cannot find module 'nock'
Require stack:
- /home/node/app/test/support/generators/bill_run.generator.js
- /home/node/app/test/support/generators/index.js
- /home/node/app/app/controllers/admin/test/test_bill_run.controller.js
- /home/node/app/app/controllers/index.js
- /home/node/app/app/routes/airbrake.routes.js
- /home/node/app/app/routes/index.js
- /home/node/app/app/plugins/router.plugin.js
- /home/node/app/app/plugins/index.js
- /home/node/app/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/node/app/test/support/generators/bill_run.generator.js:8:14)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/node/app/test/support/generators/bill_run.generator.js',
    '/home/node/app/test/support/generators/index.js',
    '/home/node/app/app/controllers/admin/test/test_bill_run.controller.js',
    '/home/node/app/app/controllers/index.js',
    '/home/node/app/app/routes/airbrake.routes.js',
    '/home/node/app/app/routes/index.js',
    '/home/node/app/app/plugins/router.plugin.js',
    '/home/node/app/app/plugins/index.js',
    '/home/node/app/server.js'
  ]
}
```

This is caused by the `BillRunGenerator` requiring `nock` which prior to this change was only a `devDependency`. Moving it to being a main dependencyshould resolve the error.